# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'RxSwift+UITableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'

  # Pods for RxSwift+UITableView

end
